### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by ari3s** [vifactor/repostat#28]
unit2 test reports the following failures (Python 2.7.15 was used):

```
======================================================================
FAIL: test_changes_history (test.TestPygitMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jberan/git/repostat/test.py", line 579, in test_changes_history
    t, expected_record, self.gs.changes_history[t]))
AssertionError: 1186502755: {u'files': 1, u'lines': 818, u'del': 0, u'ins': 0} vs. {u'files': 2, u'lines': 818, u'del': 141, u'ins': 141}

======================================================================
FAIL: test_rev_list (test.TestPygitMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jberan/git/repostat/test.py", line 603, in test_rev_list
    self.assertListEqual(expected_data, actual_data)
AssertionError: Lists differ: [(1539032340L, '1e80d967ac61c7... != [(1539032340, '1e80d967ac61c7f...

First differing element 181:
(1261815612L, 'b1dd28ed04df03bc06206bededc46b70cc57afa8')
(1261644398, 'a61bae76cbd8c8e76bc486110d21240fd203bf1c')

Diff is 50476 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 15 tests in 14.476s

FAILED (failures=4)

```

**Comment by vifactor** [comment]
Hi! Thanks for reporting. You are right, tests fail, but they are not usable anymore: were used to migrate from raw git-subprocess calls to pygit2, now obsolete. I think the best would be to skip the failing ones. I'll check what can be done.

**Comment by vifactor** [comment]
Just skipped the failing ones. Those are not "smoke" unit tests, so they are not supposed to always pass.
Unit tests are a far future for this project.
