### ISSUE TITLE
Deploy project on Ubuntu ppa

### ISSUE THREAD

**Issue by vifactor** [vifactor/repostat#60]

**Comment by vifactor** [comment]
PPA created and attempt to upload source has been made
https://launchpad.net/~vifactor/+archive/ubuntu/ppa

**Comment by vifactor** [comment]
Build dependencies need to be adjusted:
I: pybuild base:217: python3.6 setup.py clean 
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from tools import Configuration
  File "/<<PKGBUILDDIR>>/tools/__init__.py", line 2, in <module>
    from .gitstatistics import GitStatistics
  File "/<<PKGBUILDDIR>>/tools/gitstatistics.py", line 3, in <module>
    import pygit2 as git
ModuleNotFoundError: No module named 'pygit2'
E: pybuild pybuild:336: clean: plugin distutils failed with: exit code=1: python3.6 setup.py clean 
dh_auto_clean: pybuild --clean -i python{version} -p 3.6 returned exit code 13
debian/rules:7: recipe for target 'clean' failed
make: *** [clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 20190624-1424

Finished
--------

E: Build failure (dpkg-buildpackage died)

**Comment by vifactor** [comment]
Still not resolved

> Traceback (most recent call last):
>   File "setup.py", line 2, in <module>
>     from config import Configuration
>   File "/<<PKGBUILDDIR>>/config/__init__.py", line 1, in <module>
>     from .configuration import Configuration, ConfigurationException, UsageException
>   File "/<<PKGBUILDDIR>>/config/configuration.py", line 9, in <module>
>     from tools import get_pipe_output
>   File "/<<PKGBUILDDIR>>/tools/__init__.py", line 2, in <module>
>     from .gitstatistics import GitStatistics
>   File "/<<PKGBUILDDIR>>/tools/gitstatistics.py", line 3, in <module>
>     import pygit2 as git
> ModuleNotFoundError: No module named 'pygit2'
> E: pybuild pybuild:336: clean: plugin distutils failed with: exit code=1: python3.6 setup.py clean

**Comment by vifactor** [comment]
Finally, it was accepted by ppa build system!
https://launchpad.net/~vifactor/+archive/ubuntu/ppa
