### ISSUE TITLE
Crash: Signature cannot have an empty name or email

### ISSUE THREAD

**Issue by multiholle** [vifactor/repostat#84]
```
Collecting data...
Fetching authors info...
Traceback (most recent call last):
  File "XXX/env/bin/repostat", line 11, in <module>
    load_entry_point('repo-stat', 'console_scripts', 'repostat')()
  File "XXX/env/src/mho/analysis/repostat.py", line 60, in main
    repository_statistics = GitStatistics(config.git_repository_path)
  File "XXX/env/src/xxx/analysis/gitstatistics.py", line 146, in __init__
    self.authors = self.fetch_authors_info()
  File "XXX/env/src/mho/tools/timeit.py", line 15, in wrapper
    result = method(*args)
  File "XXX/env/src/xxx/analysis/gitstatistics.py", line 247, in fetch_authors_info
    author_name = self.signature_mapper(child_commit.author).name
  File "XXX/env/src/xxx/analysis/gitstatistics.py", line 134, in <lambda>
    self.signature_mapper = lambda signature: self.mailmap.resolve_signature(signature)
ValueError: failed to parse signature - Signature cannot have an empty name or email
```

**Comment by vifactor** [comment]
Hi, thank you for reporting. I was able to create a commit with an empty author's email. Could you confirm that this is the case for the repo you had analysed?

**Comment by vifactor** [comment]
@multiholle , I have provided the fix. Would be grateful if you could check.
